### PR TITLE
Added a molecule test.

### PR DESCRIPTION
**Pull request by janvanmansum**
The PR adds a [molecule](https://molecule.readthedocs.io/en/latest/) test. It is work in progress, but I would appreciate any feedback. Currently, I am unable to deploy Dataverse in Payara, so I am using the old Glassfish 4.1.

To test:

1. Install [Vagrant](https://www.vagrantup.com/), [VirtualBox](https://www.virtualbox.org/).
2. Install molecule and the vagrant driver:

        pip install molecule molecule-vagrant

3. Execute: create, converge and verify:
 
        molecule create
        molecule converge
        molecule verify

`molecule test` will fail at the idempotence check, as the role is not yet idempotent.

### CODE REVIEW

**Comment by donsizemore** [comment]
as of this writing I get:

```
    TASK [http://localhost:8080 is accessible] *************************************
    ok: [centos8] => {
        "changed": false,
        "msg": "All assertions passed"
    }
```

though I might suggest a deeper check such as http://localhost:8080/dataverse.xhtml ?

Looks great!

**Comment by janvanmansum** [comment]
Good point, I added that check. I found that `mol test` will not complete successfully though. After taking forever it will fail at the idempotence step, presumably because the role is not idempotent yet. I have added alternative commands for testing to the cover message of this PR.

**Comment by janvanmansum** [comment]
Hi @donsizemore, IMO this PR is ready for merge. Please, let me know if you think it needs more work.

**Comment by donsizemore** [comment]
Merged. Thank you!

**Pull request merged**
