### PR TITLE
introduce dataverse_misc_files_dir variable for /opt/dv and create it…

### PR DESCRIPTION
**Pull request by pallinger**
introduce dataverse_misc_files_dir variable for /opt/dv and create it during prereq, else language and handle config will fail later

### CODE REVIEW

**Comment by donsizemore** [comment]
@pallinger this looks good, but please don't merge this until I can duplicate your group_var addition to the YML files beneath `tests/`? will do that today.

**Comment by pallinger** [comment]
> @pallinger this looks good, but please don't merge this until I can duplicate your group_var addition to the YML files beneath `tests/`? will do that today.

@donsizemore  I did the group_vars additions, please check them!

**Comment by donsizemore** [comment]
@pallinger I submitted a PR to your branch which should get the `lang_directory` and `admcredfile` templating bits as well? (unless these will break as nested variables)

**Comment by pallinger** [comment]
> @pallinger I submitted a PR to your branch which should get the `lang_directory` and `admcredfile` templating bits as well? (unless these will break as nested variables)

@donsizemore I merged it, so you can merge this if you think it is done.

**Pull request merged**
