### PR TITLE
Restore dataverse-apache.yml idempotence

### PR DESCRIPTION
**Pull request by janvanmansum**
# Problem
Commit a2622593a9c745869f66c6cbbd6c88f6d914842a made dataverse-apache.yml non-idempotent because the `semanage fcontext` call is not idempotent. 

# Solution
* Implemented a solution by using Ansible's SELinux modules `ansible.posix.seboolean` and `sefcontext`
* Also changed the setting of the SELinux booleans to using this module (not strictly required).
* Left the restorecon call a `shell` command, as I am not sure how to Ansible-fy it.

# Aside
To use the Ansible SELinux module two python modules are required. I only know how to install those on RedHat 7 and 8, not sure how to do that on Debian. Is SELinux support required in Debian at all? I haven't been able to provision ubuntu-16.04 successfully with the molecule test (hence the commented out section in `molecule/default/molecule.yml`.  Debian is not a use-case for us, but I am willing to help if anybody has a specific version/flavor of Debian that they need to provision. It would be great if a successful molecule platform could be added for it.

### CODE REVIEW

**Comment by donsizemore** [comment]
There I go, breaking things again... thank you for the pull request!

Dataverse is mostly-officially tested on RHEL/CentOS 8 (the latter soon to be CentOS 8-Stream) so that's been my target OS family.

I myself don't have the cycles to maintain the Debian portion of dataverse-ansible but I approve of the Debian/Ubuntu ecosystem, this repo is open source and I always welcome pull requests.

**Comment by donsizemore** [comment]
@janvanmansum I'm afraid I'm reverting this pull request merge. Even once I've added an `ansible-galaxy collection install ansible.posix` shell command to prereqs.yml, the run still dies:

```
ERROR! couldn't resolve module/action 'ansible.posix.seboolean'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/etc/ansible/roles/dataverse/tasks/dataverse-apache.yml': line 26, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: set SELinux boolean
  ^ here
```

I don't see anything wrong with the syntax?

**Comment by donsizemore** [comment]
@janvanmansum oh, and one caution about idempotence: Ansible roles "should" be idempotent, but the Dataverse installer itself is not - in particular there's a "superUser" API toggle in the setup routine which will remove the dataverseAdmin user's superUser status on every other run, which can cause all sorts of problems.

**Comment by janvanmansum** [comment]
Strange, I am using Ansible 2.10.3 and AFAIK I didn't have to do any extra steps to use `ansible.posix.seboolean`. I'll investigate and will hopefully do a new PR soon.

**Pull request merged**
